repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python commit_check.py
        language: python
        types: [python]
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=150, app]
        language_version: python3
