"""created at and updated at added to all tables

Revision ID: 04c90d71bacf
Revises: ef7d2a39d5ec
Create Date: 2024-08-04 18:04:31.773841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04c90d71bacf"
down_revision: Union[str, None] = "ef7d2a39d5ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("categories", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("severity", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("severity", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("subcategories", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True))
    op.add_column("subcategories", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "tickets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tickets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tickets",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tickets",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("subcategories", "updated_at")
    op.drop_column("subcategories", "created_at")
    op.drop_column("severity", "updated_at")
    op.drop_column("severity", "created_at")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    # ### end Alembic commands ###
