"""Update on severity level

Revision ID: 2cc59a51f8eb
Revises: b331578d546c
Create Date: 2024-08-04 13:49:52.614046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cc59a51f8eb"
down_revision: Union[str, None] = "b331578d546c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "severity", ["level"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "severity", type_="unique")
    # ### end Alembic commands ###
