"""new relationship

Revision ID: 93f8927a3e88
Revises: 1e07401ef7a2
Create Date: 2024-08-04 22:51:42.115225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93f8927a3e88"
down_revision: Union[str, None] = "1e07401ef7a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tickets_category_id_fkey", "tickets", type_="foreignkey")
    op.drop_constraint("tickets_subcategory_id_fkey", "tickets", type_="foreignkey")
    op.drop_column("tickets", "category_id")
    op.drop_column("tickets", "subcategory_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("subcategory_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column("tickets", sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key("tickets_subcategory_id_fkey", "tickets", "subcategories", ["subcategory_id"], ["id"])
    op.create_foreign_key("tickets_category_id_fkey", "tickets", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###
