"""comment columns on tickets

Revision ID: 9de4285d6f9a
Revises: 93f8927a3e88
Create Date: 2024-08-05 03:06:53.149662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9de4285d6f9a"
down_revision: Union[str, None] = "93f8927a3e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column("tickets", sa.Column("comment_user", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "comment_user")
    op.drop_column("tickets", "comment")
    # ### end Alembic commands ###
