"""update on parent_id on categories

Revision ID: 9ec438061c2a
Revises: 2cc59a51f8eb
Create Date: 2024-08-04 14:17:03.603039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ec438061c2a"
down_revision: Union[str, None] = "2cc59a51f8eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
