"""Update on level column from severity

Revision ID: b331578d546c
Revises: 3f0464564335
Create Date: 2024-08-04 13:47:31.948219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b331578d546c"
down_revision: Union[str, None] = "3f0464564335"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("severity_level_key", "severity", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("severity_level_key", "severity", ["level"])
    # ### end Alembic commands ###
