"""Relationships

Revision ID: ef7d2a39d5ec
Revises: 9ec438061c2a
Create Date: 2024-08-04 17:41:33.361833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef7d2a39d5ec"
down_revision: Union[str, None] = "9ec438061c2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_categories",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id", "category_id"),
    )
    op.create_table(
        "ticket_subcategories",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("subcategory_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["subcategories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id", "subcategory_id"),
    )
    op.drop_constraint("categories_parent_id_fkey", "categories", type_="foreignkey")
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key("categories_parent_id_fkey", "categories", "categories", ["parent_id"], ["id"])
    op.drop_table("ticket_subcategories")
    op.drop_table("ticket_categories")
    # ### end Alembic commands ###
